skillMetadata:
  sections:
    - name: Authentification with Mycroft REST API
      fields:
        - type: label
          label: >
            <p>
            In order to communicate with each other, this skill and the Mycroft REST API requires an authentication based on an API key.<br/>
            This API key could be found within the Mycroft REST API configuration file.
            <p/>
        - name: api_key
          type: password
          label: API authentication key
          value: ""
